[tool.poetry]
name = "menage_jupyter"
version = "0.1.0"
description = "Simple package to menage jupyter files"
authors = ["Bartłomiej Chwiłkowski <bartekchwilkowski@gmail.com>"]
license = "CC BY"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
